package config

import (
	"bytes"
	"crypto/ed25519"
	"crypto/rand"
	"os"
	"path/filepath"
	"testing"

	"github.com/spf13/viper"
	xssh "golang.org/x/crypto/ssh"
)

func TestLoadGitDefaultsAndNormalization(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	publicKey := testAuthorizedKey(t)

	viper.Reset()
	SetDefaultConfig(bytes.NewBufferString(`
git:
  default_client:
    user: " alice "
  users:
    " alice ":
      public_keys:
        - "` + publicKey + `"
  repos:
    " team/demo.git ":
      public_read: false
      readers:
        - " bob "
      writers:
        - " alice "
`))
	t.Cleanup(viper.Reset)

	if err := Init(""); err != nil {
		t.Fatalf("init config: %v", err)
	}

	cfg, err := Load()
	if err != nil {
		t.Fatalf("load config: %v", err)
	}

	if cfg.Git.RepoRoot != filepath.Join(home, ".nalvin", "git-repos") {
		t.Fatalf("expected default repo root, got %q", cfg.Git.RepoRoot)
	}
	if cfg.Git.SSH.Addr != "127.0.0.1:4222" {
		t.Fatalf("expected default ssh addr, got %q", cfg.Git.SSH.Addr)
	}
	if !cfg.Git.SSH.Enabled {
		t.Fatal("expected git ssh to default enabled=true")
	}
	if cfg.Git.SSH.HostKeyPath != filepath.Join(home, ".nalvin", "git", "ssh_host_ed25519") {
		t.Fatalf("expected default host key path, got %q", cfg.Git.SSH.HostKeyPath)
	}
	if cfg.Git.DefaultClient.User != "alice" {
		t.Fatalf("expected normalized default client user, got %q", cfg.Git.DefaultClient.User)
	}
	if cfg.Git.DefaultClient.PrivateKeyPath != filepath.Join(home, ".nalvin", "git", "id_nalvin") {
		t.Fatalf("expected default private key path, got %q", cfg.Git.DefaultClient.PrivateKeyPath)
	}
	if cfg.Git.DefaultClient.AuthorName != "alice" {
		t.Fatalf("expected default author name to mirror user, got %q", cfg.Git.DefaultClient.AuthorName)
	}
	if cfg.Git.DefaultClient.AuthorEmail != "alice@nalvin.local" {
		t.Fatalf("expected default author email, got %q", cfg.Git.DefaultClient.AuthorEmail)
	}
	if !cfg.Git.RepoDefaults.PublicRead {
		t.Fatal("expected default public_read to be true")
	}
	if len(cfg.Git.RepoDefaults.DefaultWriters) != 1 || cfg.Git.RepoDefaults.DefaultWriters[0] != "alice" {
		t.Fatalf("expected default writers to inherit default client user, got %#v", cfg.Git.RepoDefaults.DefaultWriters)
	}

	userCfg, ok := cfg.Git.Users["alice"]
	if !ok {
		t.Fatalf("expected normalized git user key, got %#v", cfg.Git.Users)
	}
	foundExplicitKey := false
	for _, key := range userCfg.PublicKeys {
		if key == publicKey {
			foundExplicitKey = true
			break
		}
	}
	if !foundExplicitKey {
		t.Fatalf("expected configured git user public key to be preserved, got %#v", userCfg.PublicKeys)
	}

	repoCfg, ok := cfg.Git.Repos["team/demo"]
	if !ok {
		t.Fatalf("expected normalized repo key, got %#v", cfg.Git.Repos)
	}
	if repoCfg.PublicRead == nil || *repoCfg.PublicRead {
		t.Fatal("expected repo override public_read=false")
	}
	if len(repoCfg.Readers) != 1 || repoCfg.Readers[0] != "bob" {
		t.Fatalf("expected normalized readers, got %#v", repoCfg.Readers)
	}
	if len(repoCfg.Writers) != 1 || repoCfg.Writers[0] != "alice" {
		t.Fatalf("expected normalized writers, got %#v", repoCfg.Writers)
	}
}

func testAuthorizedKey(t *testing.T) string {
	t.Helper()

	publicKey, _, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("generate ed25519 key: %v", err)
	}

	sshPublicKey, err := xssh.NewPublicKey(publicKey)
	if err != nil {
		t.Fatalf("create ssh public key: %v", err)
	}
	return string(bytes.TrimSpace(xssh.MarshalAuthorizedKey(sshPublicKey)))
}

func TestGitConfigDefaultsRespectExplicitEmptyPrivateKeyPath(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	configDir := filepath.Join(home, ".nalvin")
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		t.Fatalf("mkdir config dir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(configDir, "config.yaml"), []byte(`
git:
  default_client:
    user: alice
    private_key_path: ""
`), 0o644); err != nil {
		t.Fatalf("write config file: %v", err)
	}

	viper.Reset()
	SetDefaultConfig(bytes.NewBufferString("git:\n  default_client:\n    host: 127.0.0.1\n"))
	t.Cleanup(viper.Reset)

	if err := Init(""); err != nil {
		t.Fatalf("init config: %v", err)
	}

	cfg, err := Load()
	if err != nil {
		t.Fatalf("load config: %v", err)
	}
	if cfg.Git.DefaultClient.PrivateKeyPath != "" {
		t.Fatalf("expected explicit empty private_key_path to be preserved, got %q", cfg.Git.DefaultClient.PrivateKeyPath)
	}
}

func TestGitConfigAutoProvisionDefaultClientIdentity(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	viper.Reset()
	SetDefaultConfig(bytes.NewBufferString("git:\n  ssh:\n    enabled: true\n"))
	t.Cleanup(viper.Reset)

	if err := Init(""); err != nil {
		t.Fatalf("init config: %v", err)
	}

	cfg, err := Load()
	if err != nil {
		t.Fatalf("load config: %v", err)
	}

	if cfg.Git.DefaultClient.User != "nalvin" {
		t.Fatalf("expected autogenerated default git user, got %q", cfg.Git.DefaultClient.User)
	}
	if cfg.Git.DefaultClient.PrivateKeyPath != filepath.Join(home, ".nalvin", "git", "id_nalvin") {
		t.Fatalf("expected autogenerated private key path, got %q", cfg.Git.DefaultClient.PrivateKeyPath)
	}
	if _, err := os.Stat(cfg.Git.DefaultClient.PrivateKeyPath); err != nil {
		t.Fatalf("expected autogenerated private key to exist: %v", err)
	}
	if _, err := os.Stat(cfg.Git.DefaultClient.PrivateKeyPath + ".pub"); err != nil {
		t.Fatalf("expected autogenerated public key to exist: %v", err)
	}
	if got := cfg.Git.Users["nalvin"].PublicKeys; len(got) == 0 {
		t.Fatalf("expected autogenerated git user public key, got %#v", cfg.Git.Users)
	}
	if len(cfg.Git.RepoDefaults.DefaultWriters) != 1 || cfg.Git.RepoDefaults.DefaultWriters[0] != "nalvin" {
		t.Fatalf("expected default writers to inherit autogenerated user, got %#v", cfg.Git.RepoDefaults.DefaultWriters)
	}
}
